apiVersion: v2
name: warre
description: A Helm chart for warre
type: application
version: 2.1.6
appVersion: 4.1.0-2-g3f24bc7
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
