apiVersion: v2
name: warre
description: A Helm chart for warre
type: application
version: 4.0.1
appVersion: 5.0.1-1-g0755371
sources:
- https://github.com/NeCTAR-RC/warre-helm.git
dependencies:
- name: nectarlib
  version: 3.2.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
