apiVersion: v2
name: warre
description: A Helm chart for warre
type: application
version: 1.1.17
appVersion: 1.0.0-38-g27d7982
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
