apiVersion: v2
name: warre
description: A Helm chart for warre
type: application
version: 1.1.19
appVersion: 1.0.0-40-g06cd091
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
