apiVersion: v2
name: warre
description: A Helm chart for warre
type: application
version: 2.4.1
appVersion: 5.0.0-4-gaa7bf30
sources:
- https://github.com/NeCTAR-RC/warre-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.23.0
