apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warre.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  warre.conf: |
{{ include "warre-conf" . | indent 4 }}
