apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "warre.fullname" . }}-db-sync
  labels:
    {{- include "warre.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
        {{- include "warre.vaultAnnotations" . | nindent 8 }}
      labels:
        {{- include "warre.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "warre.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - warre-manage
            - db
            - upgrade
          volumeMounts:
            - name: {{ include "warre.fullname" . }}
              mountPath: "/etc/warre/"
      volumes:
        - name: {{ include "warre.fullname" . }}
          configMap:
            name: {{ include "warre.fullname" . }}
