{{- if .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "warre.fullname" . }}-worker
  labels:
    {{- include "warre.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable | default 0 }}
  selector:
    matchLabels:
      {{- include "warre.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
